/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_sleuthkit_autopsy_scalpel_jni_ScalpelCarver */

#ifndef _Included_org_sleuthkit_autopsy_scalpel_jni_ScalpelCarver
#define _Included_org_sleuthkit_autopsy_scalpel_jni_ScalpelCarver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_sleuthkit_autopsy_scalpel_jni_ScalpelCarver
 * Method:    carveNat
 * Signature: (Ljava/lang/String;Lorg/sleuthkit/datamodel/ReadContentInputStream;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_sleuthkit_autopsy_scalpel_jni_ScalpelCarver_carveNat
  (JNIEnv *, jclass, jstring, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
